// Pregenerated span draw routines
// Generated by zxmaze3dgenprecalc.Ht4x4AsmGenPrecalc 

// Offsets to span draw routines entry points
extern int span_func_tbl[192];

#asm
_draw_24_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_16_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_8_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end0:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

	ret
_draw_24_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_17_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_9_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_1_cells_end1:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_18_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_10_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_2_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end2:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_19_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_11_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_3_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end3:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_20_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_12_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_4_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end4:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_21_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_13_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_5_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end5:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_23_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_22_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_15_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_14_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_7_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_6_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end6:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
_draw_24_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_23_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_22_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_21_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_20_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_19_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_18_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_17_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_16_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_15_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_14_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_13_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_12_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_11_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_10_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_9_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_8_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b

	; advance HL appropriately for 8-aligned row of blocks
	; first row of the 8-group of rows of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block (-7), but next 8-group of rows of blocks
	inc h

_draw_7_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_6_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_5_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_4_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_3_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_2_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

_draw_1_cells_end7:
	; hl points to screen
	ld (hl),c		; 7 T
	inc h			; 4 T
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	inc h
	ld (hl),c
	inc h
	ld (hl),e
	inc h
	ld (hl),d
	inc h
	ld (hl),b
	
	; advance HL appropriately for non-8 aligned row of blocks
	; next row of blocks
	ld a,32
	add	l
	ld l,a
	; back to first row of the block
	ld a,-7
	add	h
	ld h,a

	ret
._span_func_tbl
	defw _draw_1_cells_end0
	defw _draw_1_cells_end1
	defw _draw_1_cells_end2
	defw _draw_1_cells_end3
	defw _draw_1_cells_end4
	defw _draw_1_cells_end5
	defw _draw_1_cells_end6
	defw _draw_1_cells_end7
	defw _draw_2_cells_end0
	defw _draw_2_cells_end1
	defw _draw_2_cells_end2
	defw _draw_2_cells_end3
	defw _draw_2_cells_end4
	defw _draw_2_cells_end5
	defw _draw_2_cells_end6
	defw _draw_2_cells_end7
	defw _draw_3_cells_end0
	defw _draw_3_cells_end1
	defw _draw_3_cells_end2
	defw _draw_3_cells_end3
	defw _draw_3_cells_end4
	defw _draw_3_cells_end5
	defw _draw_3_cells_end6
	defw _draw_3_cells_end7
	defw _draw_4_cells_end0
	defw _draw_4_cells_end1
	defw _draw_4_cells_end2
	defw _draw_4_cells_end3
	defw _draw_4_cells_end4
	defw _draw_4_cells_end5
	defw _draw_4_cells_end6
	defw _draw_4_cells_end7
	defw _draw_5_cells_end0
	defw _draw_5_cells_end1
	defw _draw_5_cells_end2
	defw _draw_5_cells_end3
	defw _draw_5_cells_end4
	defw _draw_5_cells_end5
	defw _draw_5_cells_end6
	defw _draw_5_cells_end7
	defw _draw_6_cells_end0
	defw _draw_6_cells_end1
	defw _draw_6_cells_end2
	defw _draw_6_cells_end3
	defw _draw_6_cells_end4
	defw _draw_6_cells_end5
	defw _draw_6_cells_end6
	defw _draw_6_cells_end7
	defw _draw_7_cells_end0
	defw _draw_7_cells_end1
	defw _draw_7_cells_end2
	defw _draw_7_cells_end3
	defw _draw_7_cells_end4
	defw _draw_7_cells_end5
	defw _draw_7_cells_end6
	defw _draw_7_cells_end7
	defw _draw_8_cells_end0
	defw _draw_8_cells_end1
	defw _draw_8_cells_end2
	defw _draw_8_cells_end3
	defw _draw_8_cells_end4
	defw _draw_8_cells_end5
	defw _draw_8_cells_end6
	defw _draw_8_cells_end7
	defw _draw_9_cells_end0
	defw _draw_9_cells_end1
	defw _draw_9_cells_end2
	defw _draw_9_cells_end3
	defw _draw_9_cells_end4
	defw _draw_9_cells_end5
	defw _draw_9_cells_end6
	defw _draw_9_cells_end7
	defw _draw_10_cells_end0
	defw _draw_10_cells_end1
	defw _draw_10_cells_end2
	defw _draw_10_cells_end3
	defw _draw_10_cells_end4
	defw _draw_10_cells_end5
	defw _draw_10_cells_end6
	defw _draw_10_cells_end7
	defw _draw_11_cells_end0
	defw _draw_11_cells_end1
	defw _draw_11_cells_end2
	defw _draw_11_cells_end3
	defw _draw_11_cells_end4
	defw _draw_11_cells_end5
	defw _draw_11_cells_end6
	defw _draw_11_cells_end7
	defw _draw_12_cells_end0
	defw _draw_12_cells_end1
	defw _draw_12_cells_end2
	defw _draw_12_cells_end3
	defw _draw_12_cells_end4
	defw _draw_12_cells_end5
	defw _draw_12_cells_end6
	defw _draw_12_cells_end7
	defw _draw_13_cells_end0
	defw _draw_13_cells_end1
	defw _draw_13_cells_end2
	defw _draw_13_cells_end3
	defw _draw_13_cells_end4
	defw _draw_13_cells_end5
	defw _draw_13_cells_end6
	defw _draw_13_cells_end7
	defw _draw_14_cells_end0
	defw _draw_14_cells_end1
	defw _draw_14_cells_end2
	defw _draw_14_cells_end3
	defw _draw_14_cells_end4
	defw _draw_14_cells_end5
	defw _draw_14_cells_end6
	defw _draw_14_cells_end7
	defw _draw_15_cells_end0
	defw _draw_15_cells_end1
	defw _draw_15_cells_end2
	defw _draw_15_cells_end3
	defw _draw_15_cells_end4
	defw _draw_15_cells_end5
	defw _draw_15_cells_end6
	defw _draw_15_cells_end7
	defw _draw_16_cells_end0
	defw _draw_16_cells_end1
	defw _draw_16_cells_end2
	defw _draw_16_cells_end3
	defw _draw_16_cells_end4
	defw _draw_16_cells_end5
	defw _draw_16_cells_end6
	defw _draw_16_cells_end7
	defw _draw_17_cells_end0
	defw _draw_17_cells_end1
	defw _draw_17_cells_end2
	defw _draw_17_cells_end3
	defw _draw_17_cells_end4
	defw _draw_17_cells_end5
	defw _draw_17_cells_end6
	defw _draw_17_cells_end7
	defw _draw_18_cells_end0
	defw _draw_18_cells_end1
	defw _draw_18_cells_end2
	defw _draw_18_cells_end3
	defw _draw_18_cells_end4
	defw _draw_18_cells_end5
	defw _draw_18_cells_end6
	defw _draw_18_cells_end7
	defw _draw_19_cells_end0
	defw _draw_19_cells_end1
	defw _draw_19_cells_end2
	defw _draw_19_cells_end3
	defw _draw_19_cells_end4
	defw _draw_19_cells_end5
	defw _draw_19_cells_end6
	defw _draw_19_cells_end7
	defw _draw_20_cells_end0
	defw _draw_20_cells_end1
	defw _draw_20_cells_end2
	defw _draw_20_cells_end3
	defw _draw_20_cells_end4
	defw _draw_20_cells_end5
	defw _draw_20_cells_end6
	defw _draw_20_cells_end7
	defw _draw_21_cells_end0
	defw _draw_21_cells_end1
	defw _draw_21_cells_end2
	defw _draw_21_cells_end3
	defw _draw_21_cells_end4
	defw _draw_21_cells_end5
	defw _draw_21_cells_end6
	defw _draw_21_cells_end7
	defw _draw_22_cells_end0
	defw _draw_22_cells_end1
	defw _draw_22_cells_end2
	defw _draw_22_cells_end3
	defw _draw_22_cells_end4
	defw _draw_22_cells_end5
	defw _draw_22_cells_end6
	defw _draw_22_cells_end7
	defw _draw_23_cells_end0
	defw _draw_23_cells_end1
	defw _draw_23_cells_end2
	defw _draw_23_cells_end3
	defw _draw_23_cells_end4
	defw _draw_23_cells_end5
	defw _draw_23_cells_end6
	defw _draw_23_cells_end7
	defw _draw_24_cells_end0
	defw _draw_24_cells_end1
	defw _draw_24_cells_end2
	defw _draw_24_cells_end3
	defw _draw_24_cells_end4
	defw _draw_24_cells_end5
	defw _draw_24_cells_end6
	defw _draw_24_cells_end7

#endasm
